language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - db=postgres

before_script:
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install
    - psql -c 'create database ouzo_test' -U postgres
    - environment=test ./db.sh db:migrate

script:
    - phpunit --configuration phpunit.xml test
